#pragma config(Motor,  motorA,          liftmotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftmotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          rightmotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Since August 21th, 2018 */
// ALLEN TAO //
/* Completed by yours truly, August 23, 2018 */

// Not necessarily optimally programmed, coded with the intention of mastering PID control.

// [ * ] Note, the lift of the bot must be calibrated in a way such that the fork touches the ground by raising and dropped the lift all the way.

void sustainLift(int pos)
{
	float liftKp = 0.2;

	float lifterror;
	float liftfinalpower;

	if(pos > nMotorEncoder[liftmotor])
	{
		lifterror = pos - nMotorEncoder[liftmotor];
		liftfinalpower = lifterror * liftKp;
		motor[liftmotor] = liftfinalpower;
	}
	else if(pos < nMotorEncoder[liftmotor])
	{
		lifterror = pos - nMotorEncoder[liftmotor];
		liftfinalpower = lifterror * liftKp;
		motor[liftmotor] = liftfinalpower;
	}
}
void PIDliftcontrol (int dest, float time)
{
	float Kp;
	if(dest < 150)
	{
		Kp = 0.1; // Slow drop
	}
	else
	{
		Kp = 0.3; // Fast lift
	}
	float proportion;
	float error;
	float finalpower;

	float Ki;
	if(dest < 60)
	{
		Ki = 0.01;
	}
	else
	{
		Ki = 0.5;
	}
	//float integralraw;
	//float integral;
	//int integralactivezone = 30;

	bool rtime = true;

	clearTimer(T2);

	while(time1[T2] < time)
	{
		error = dest - nMotorEncoder[liftmotor];

		proportion = (Kp*error);

		finalpower = proportion; // Ideally, Proportion + Integral + Derivative

		motor[liftmotor] = finalpower;

		if(rtime)
		{
			clearTimer(T2);
		}

		if(abs(error) < 50)
		{
			rtime = false;
		}
		wait1Msec(40);
	}
}

task main()
{
	nMotorEncoder[liftmotor] = 0;
	nMotorEncoder[leftmotor] = 0;
	nMotorEncoder[rightmotor] = 0;

	int motorPos = nMotorEncoder[liftmotor];


	while(true)
	{

		if(getIRRemoteButtons(S4) == 1)
		{
			motor[leftmotor] = 127;
		}
		else if(getIRRemoteButtons(S4) == 2)
		{
			motor[leftmotor] = -127;
		}
		else if(getIRRemoteButtons(S4) == 3)
		{
			motor[rightmotor] = 127;
		}
		else if(getIRRemoteButtons(S4) == 4)
		{
			motor[rightmotor] = -127;
		}
		else if(getIRRemoteButtons(S4) == 5)
		{
			motor[leftmotor] = 127;
			motor[rightmotor] = 127;
		}
		else if(getIRRemoteButtons(S4) == 6)
		{
			motor[leftmotor] = 127;
			motor[rightmotor] = -127;
		}
		else if(getIRRemoteButtons(S4) == 7)
		{
			motor[leftmotor] = -127;
			motor[rightmotor] = 127;
		}
		else if(getIRRemoteButtons(S4) == 8)
		{
			motor[leftmotor] = -127;
			motor[rightmotor] = -127;
		}
		else if(getIRRemoteButtons(S4) == 9)
		{
			PIDliftcontrol(230, 1000);
			motorPos = 230; // Set motorPos to full lift position(230)

		}
		else if(getIRRemoteButtons(S4) == 0)
		{
			motor[leftmotor] = 0;
			motor[rightmotor] = 0;

			sustainLift(motorPos);
		}
		else
		{
			PIDliftcontrol(15, 1000);
			motorPos = 15; // Set motorPos to full drop position(15)
		}
		wait1Msec(40);
	}


}
